[project]
name = "osm-to-parquet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "ipywidgets>=8.1.7",
    "jupyterlab>=4.4.4",
    "more-itertools>=10.7.0",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "pip>=25.1.1",
    "protobuf>=6.31.1",
    "pyarrow>=20.0.0",
    "pyspark>=4.0.0",
    "tqdm>=4.67.1",
]
